version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retina_scan

  web:
    build: .
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - mediaroot:/media_root
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  dbdata:
  mediaroot: