# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('icd_code', models.CharField(blank=True, max_length=15, null=True)),
                ('json', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(height_field='height_field', upload_to='images/', width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True)),
                ('name', models.TextField()),
                ('info', models.TextField(blank=True, null=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_module.Examination')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.TextField()),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_module.ImageSeries'),
        ),
        migrations.AddField(
            model_name='examination',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_module.Person'),
        ),
        migrations.AddField(
            model_name='description',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_module.Examination'),
        ),
        migrations.AddField(
            model_name='description',
            name='key_words',
            field=models.ManyToManyField(to='data_module.KeyWords'),
        ),
    ]
